### PR TITLE
Update runtime spec

### PR DESCRIPTION
**Pull request by xw19**

### CODE REVIEW

**Comment by xw19** [comment]
@saschagrunert PTAL

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
I guess you don’t have to keep it up to date? I’m a bit confused by those changes.

**Comment by xw19** [comment]
@saschagrunert I guess you are right. I didn't need this change. I will try to be more careful next time

**Comment by saschagrunert** [comment]
@xw19 let's close this PR then?

**Comment by xw19** [comment]
Okay

**Pull request closed without merging**
