### PR TITLE
Update formatting for source and header files

### PR DESCRIPTION
**Pull request by Ilya-source**
Hello!

I want to introduce some updates to string handling: move from %s formatting to f-string.
That makes the code a bit more readable and faster.

Also, I changed how source and header files are written (basically, I just moved to the `writelines` method).

I hope you will find those changes useful.

### CODE REVIEW

**Comment by Ilya-source** [comment]
@giuseppe could you review this pr?

**Review by flouthoc — COMMENTED** [review]
I have no clue about `write` vs `append` in python. @Ilya-source does it creates a significant difference ?

**Review by flouthoc — COMMENTED** [review]
PR LGTM overall apart from the one doubt above.

**Comment by giuseppe** [comment]
@Ilya-source thanks for opening the PR, could you please open a PR for crun that uses this version of libocispec to see if there are any regressions?

**Comment by giuseppe** [comment]
actually we don't need that, I've verified the generated source is the same

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by Ilya-source** [comment]
@flouthoc 
> I have no clue about `write` vs `append` in python. @Ilya-source does it creates a significant difference ?

That makes code a bit easier to debug in python debugger, and this is [faster](https://stackoverflow.com/questions/43462126/python-reading-and-writing-to-files-write-vs-writelines-performance), of course, in this project this was not that important, because this is just a one time generation step, but still. :)

**Comment by flouthoc** [comment]
@Ilya-source Thanks for the info and the PR :)

**Pull request merged**
