### PR TITLE
Generate json_t from parsing the json string

### PR DESCRIPTION
**Pull request by xw19**
Generating the initial json_t instead of yajl_val and remove temporary function

Part of #138

### CODE REVIEW

**Review by saschagrunert — APPROVED** [review]

**Comment by saschagrunert** [comment]
@giuseppe PTAL, code LGTM

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by giuseppe** [comment]
@saschagrunert please merge to switch-to-jansson as soon as you are happy with it :-)

I think it is more important to move fast with the prototyping, we can deal with minor details later

**Comment by giuseppe** [comment]
@saschagrunert added you as a maintainer of the project

**Comment by saschagrunert** [comment]
@giuseppe thank you!

**Comment by xw19** [comment]
@saschagrunert @giuseppe Parsing of json has been converted to jansson only genration part still uses yajl by next week we should be using only jansson.

**Comment by saschagrunert** [comment]
Refers to #138

**Pull request merged**
