### PR TITLE
yajl: statically link containers/yajl clone

### PR DESCRIPTION
**Pull request by giuseppe**
libyajl is unmaintained, use the new clone to include some fixes.

Signed-off-by: Giuseppe Scrivano <gscrivan@redhat.com>

### CODE REVIEW

**Comment by giuseppe** [comment]
@rhatdan do you think we should move giuseppe/yajl under containers?  It is going to be used only for tests.

The fixes issues are not a big deal, but do cause memory leaks on errors and that is a problem with the static analysis/fuzzing work I am doing for crun

**Comment by rhatdan** [comment]
Sure you can move it there.

**Comment by giuseppe** [comment]
> Sure you can move it there.

moved and updated the PR

**Comment by giuseppe** [comment]
@rhatdan fine to merge?

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
