### PR TITLE
Sync c and rust bindings with upstream for zOS specific platform config.

### PR DESCRIPTION
**Pull request by flouthoc**

### CODE REVIEW

**Comment by flouthoc** [comment]
/hold 
Seems something is wrong with latest image-spec.

**Comment by flouthoc** [comment]
I think this should be the right fix https://github.com/opencontainers/runtime-spec/pull/1117

**Comment by flouthoc** [comment]
@giuseppe @rhatdan this is resolved PTAL.

**Review by giuseppe — APPROVED** [review]
LGTM

**Pull request merged**
