### PR TITLE
Add Security Policy

### PR DESCRIPTION
**Pull request by TomSweeneyRedHat**
As the title says.

Signed-off-by: TomSweeneyRedHat <tsweeney@redhat.com>

### CODE REVIEW

**Comment by TomSweeneyRedHat** [comment]
@rhatdan PTAL

**Comment by giuseppe** [comment]
I think it is better if it follows the crun Security Policy.  libocispec is used mainly by crun

**Comment by rhatdan** [comment]
@giuseppe Does crun have a security policy?

**Comment by TomSweeneyRedHat** [comment]
The one in containers/crun had a policy already.  I left it alone and will copy that into this one.

**Comment by TomSweeneyRedHat** [comment]
@giuseppe one small change from crun's, I did "this project" -> "the libocispec project" in the first line.

**Comment by rhatdan** [comment]
LGTM

**Pull request merged**
