### PR TITLE
Move header files under ocispec/

### PR DESCRIPTION
**Pull request by ronalabraham**
A couple of header file names (read-file.h, json_common.h) are a bit generic. To avoid filename collisions, it would be nice to install the headers in a subdirectory (`ocispec/`) of the `$(includedir)`. This would also match the pattern of [yajl](https://github.com/lloyd/yajl/blob/5e3a7856e643b4d6410ddc3f84bc2f38174f2872/src/CMakeLists.txt#L85), which installs headers in `include/yajl`.

This will require some follow-up changes to [crun](https://github.com/containers/crun) to refer to the correct libocispec header file locations.

Signed-off-by: Ronal Abraham <ronalabraham@gmail.com>

### CODE REVIEW

**Review by flouthoc — COMMENTED** [review]
Could we instead add prefix `libocispec_` to generic header files, it'll be much smaller change afaics. But I'll wait for @giuseppe 's review.

**Comment by ronalabraham** [comment]
@flouthoc Yes, I think that would work for me. @giuseppe What do you prefer?

**Comment by giuseppe** [comment]
since we install these files I think it is better if we create a subdirectory.

@flouthoc if you are fine as well with the current version, please merge it :)

**Review by giuseppe — APPROVED** [review]
LGTM

**Comment by flouthoc** [comment]
> since we install these files I think it is better if we create a subdirectory.
> 
> @flouthoc if you are fine as well with the current version, please merge it :)

ah yes sounds good to me.

**Pull request merged**
