### PR TITLE
update runtime-spec to latest

### PR DESCRIPTION
**Pull request by cdoern**
Signed-off-by: Charlie Doern <cdoern@redhat.com>

### CODE REVIEW

**Comment by cdoern** [comment]
@giuseppe PTAL

**Comment by cdoern** [comment]
I am not seeing my commits in here, does that mean we already have them?

**Comment by flouthoc** [comment]
@cdoern If you are looking for `domainname` changes, I think its already in libocispec but I can see the repo is updated in this PR as well.

**Comment by giuseppe** [comment]
@cdoern LGTM, but since we are doing it, could you please update again since there are new changes in runtime-spec that we would like to have in libocispec and in crun?

**Comment by cdoern** [comment]
sure @giuseppe

**Review by flouthoc — APPROVED** [review]
LGTM

**Review by giuseppe — APPROVED** [review]

**Pull request merged**
